### ISSUE TITLE
Add Magisk 20.0 new overlay support?

### ISSUE THREAD

**Issue by Kein** [Magisk-Modules-Grave/gjf_bt#11]
So I've noticed today I'm unable to remount `/system` (as in `/`) for `rw`, any file manager would hang and use 99% CPU while logcat is full of overlay errors. Eventually, after more testing, thinking and googling and reading Magisk issues I came across explanation why this might happen:

https://github.com/topjohnwu/Magisk/issues/1936  
and  
20.0 notes:
https://github.com/topjohnwu/magisk_files/blob/2d7ddefbe4946806de1875a18247b724f5e7d4a0/notes.md

The mod works great for me so far and it eliminates a lot of clipping for my cheap TWS earbuds but at the same time I do not want to lose ability to modify `/system` when needed. Any chance you could add proper support for new Magisk?

**Comment by gjf** [comment]
This module is officially abandoned. You are free to modify it you see fit.

**Comment by Kein** [comment]
Any particular reason why? I assume you no longer own low-end device and instead bought premium ones, both phone and earbuds, that do not require you to go to great lengths to enjoy good things proper white people enjoy effortlessly every day and thus this module has no more relevance to you?
